---
title: Cathay.Blog
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Cathay.Blog,文刀刘,一个博客树洞。本博客基于Jekyll进行书写。源自生活的点点滴滴和碎碎念。
baseurl: ''
url: https://cathay.blog
author:
  name: 文刀刘
  url: https://cathay.blog/about/
  email: 9125@88.com
markdown: kramdown
include:
- _pages
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
permalink: "/post/:year:month:day.html"
paginate: 5
exclude:
- Gemfile
- Gemfile.lock
- muji.gemspec
